name: Build KytyPS5

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    env:
      BUILD_TYPE: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Visual Studio Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Install Qt 6.10.3
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10.3"
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          cache: true

      - name: Install Vulkan SDK 1.4.335.0
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.335.0
          cache: true

      - name: Verify Environment
        shell: cmd
        run: |
          echo ===== CLANG =====
          where clang-cl
          clang-cl --version

          echo ===== NINJA =====
          ninja --version

          echo ===== CMAKE =====
          cmake --version

          echo ===== QT =====
          echo Qt6_DIR=%Qt6_DIR%

          echo ===== VULKAN =====
          echo %VULKAN_SDK%

      - name: Configure
        shell: cmd
        run: |
          cmake ^
            -S src ^
            -B build ^
            -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_C_COMPILER=clang-cl ^
            -DCMAKE_CXX_COMPILER=clang-cl

      - name: Build
        shell: cmd
        run: |
          cmake --build build --target launcher --parallel

      - name: Install
        shell: cmd
        run: |
          cmake --install build --prefix build/install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KytyPS5-Windows
          path: build/install
